#!/usr/bin/env bash

APP="real_world" # name of your release

BUILD_HOST="45.33.63.117" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/tmp/edeliver/$APP/builds" # build directory on build host

#STAGING_HOSTS="45.33.63.117" # staging / test hosts separated by space
#STAGING_USER="root" # local user at staging hosts
#TEST_AT="/opt/real-world" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="45.33.63.117" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/opt/real-world" # deploy directory on production hosts

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/$BUILD_USER/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}